version: '3.8'

services:
  calculator:
    build: .
    volumes:
      - logs:/logs
    ports:
      - "8000:8000"  # Expose port for metrics scraping

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  logs:
